"""Update schools fields

Revision ID: 0366e2943536
Revises: 4a33ee6dacbe
Create Date: 2025-10-03 01:58:28.763064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0366e2943536'
down_revision = '4a33ee6dacbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'invite_code',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_schools_invite_code'), 'schools', ['invite_code'])
    op.create_unique_constraint(op.f('uq_schools_school_name'), 'schools', ['school_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_schools_school_name'), 'schools', type_='unique')
    op.drop_constraint(op.f('uq_schools_invite_code'), 'schools', type_='unique')
    op.alter_column('schools', 'invite_code',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    # ### end Alembic commands ###
